U      ← /=⊞<0.2_0.7 /+×⟜ⁿ1_2
I      ← >⌵/ℂ: # Circle
u      ← +0.1↧¤ ⊃(I0.95|⊂:0.5⇌°√)
A      ← ×⊃U(I1) # Alpha
Coords ← -1÷÷2⟜(⇡↯2)
Logo   ← ⍜°⍉(⊂⊃u A) Coords
Flag   ← ▽⊃(÷⧻:)≡↯
CFlag  ← ⍜∩°⍉(↧¤I0.95)Coords ⟜Flag

512 # Size
⊃(≡◇CFlag:PrideFlags|⊢⇌°⍉.Logo)
≡⍜°⍉⊂⊙¤            # Apply logo alpha to flags
+∩×≡(⊙:¬.)⊸⊙⊙¤ 0.3 # Tint flags with logo
+☇3[..0.05 0]      # Lighten
⊂:                 # Add logo
&gifs 1
